import type { Place, SocialStats } from '../types';

export const mockPlaces: Place[] = [
  {
    id: '1',
    name: 'Kang Ho Dong Baekjeong',
    address: '1 E 32nd St, New York, NY 10016',
    latitude: 40.7462,
    longitude: -73.9838,
    cuisineType: 'Korean',
    priceRange: '$$$',
    rating: 4.5,
    coverImage: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    tikTokUrl: 'https://www.tiktok.com/@example/video/1234567890',
    instagramUrl: 'https://www.instagram.com/p/example1/',
    reviewContent: 'The BEST Korean BBQ in NYC! The marinated short ribs literally melt in your mouth. Celebrity chef Kang Ho Dong knows what he\'s doing. The banchan spread is incredible - over 10 different sides! Pro tip: go for the combo platter and make sure to try their signature egg soufflé.',
    featured: true,
    published: true,
    hours: 'Mon-Sun: 11:30 AM - 11:00 PM',
    phone: '(212) 966-9839',
  },
  {
    id: '2',
    name: 'Sugarfish by Sushi Nozawa',
    address: '33 E 20th St, New York, NY 10003',
    latitude: 40.7387,
    longitude: -73.9883,
    cuisineType: 'Japanese',
    priceRange: '$$$',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    tikTokUrl: 'https://www.tiktok.com/@example/video/1234567891',
    instagramUrl: 'https://www.instagram.com/p/example2/',
    reviewContent: 'Trust me on this one - THE omakase experience without breaking the bank. Every piece of fish is pristine, and the warm rice is perfectly seasoned. Order the "Trust Me" menu and let the chefs work their magic. The blue crab hand roll is *chef\'s kiss*.',
    featured: true,
    published: true,
    hours: 'Mon-Sun: 11:30 AM - 10:00 PM',
  },
  {
    id: '3',
    name: 'Los Tacos No. 1',
    address: '75 9th Ave, New York, NY 10011',
    latitude: 40.7425,
    longitude: -74.0060,
    cuisineType: 'Mexican',
    priceRange: '$',
    rating: 4.6,
    coverImage: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    tikTokUrl: 'https://www.tiktok.com/@example/video/1234567892',
    reviewContent: 'If you\'re looking for authentic street tacos in NYC, this is IT. The adobada (marinated pork) tacos are life-changing. Fresh tortillas made right in front of you, perfectly charred meat, and that green salsa? Addictive. Always a line but SO worth it.',
    featured: true,
    published: true,
    hours: 'Mon-Sun: 11:00 AM - 9:00 PM',
  },
  {
    id: '4',
    name: 'Via Carota',
    address: '51 Grove St, New York, NY 10014',
    latitude: 40.7326,
    longitude: -74.0033,
    cuisineType: 'Italian',
    priceRange: '$$$',
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800',
    instagramUrl: 'https://www.instagram.com/p/example3/',
    reviewContent: 'The most romantic Italian spot in the West Village. Farm-to-table done right! The cacio e pepe is textbook perfect, and their seasonal vegetables are so good they\'ll make you love eating your greens. Don\'t skip the olive oil cake for dessert.',
    featured: false,
    published: true,
    hours: 'Mon-Sun: 5:30 PM - 11:00 PM',
  },
  {
    id: '5',
    name: 'Thai Diner',
    address: '186 Mott St, New York, NY 10012',
    latitude: 40.7215,
    longitude: -73.9956,
    cuisineType: 'Thai',
    priceRange: '$$',
    rating: 4.4,
    coverImage: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800',
    tikTokUrl: 'https://www.tiktok.com/@example/video/1234567893',
    reviewContent: 'Thai food meets NYC diner vibes and it WORKS. The khao man gai (Thai-style chicken and rice) is comfort food at its finest. Brunch here is unreal - try the Thai iced tea french toast. Yes, you read that right!',
    featured: true,
    published: true,
    hours: 'Mon-Fri: 11:00 AM - 10:00 PM, Sat-Sun: 10:00 AM - 10:00 PM',
  },
  {
    id: '6',
    name: 'Levain Bakery',
    address: '167 W 74th St, New York, NY 10023',
    latitude: 40.7799,
    longitude: -73.9782,
    cuisineType: 'Dessert',
    priceRange: '$',
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800',
    instagramUrl: 'https://www.instagram.com/p/example4/',
    reviewContent: 'These cookies are LEGENDARY. 6oz of pure chocolatey, gooey perfection. The chocolate chip walnut is the OG but the dark chocolate peanut butter chip is my personal favorite. Warm them up for 10 seconds in the microwave when you get home. Trust me.',
    featured: true,
    published: true,
    hours: 'Mon-Sun: 8:00 AM - 8:00 PM',
  },
  {
    id: '7',
    name: 'Pho Bang',
    address: '157 Mott St, New York, NY 10013',
    latitude: 40.7189,
    longitude: -73.9977,
    cuisineType: 'Vietnamese',
    priceRange: '$',
    rating: 4.3,
    coverImage: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800',
    reviewContent: 'The most authentic pho in Chinatown! The broth is simmered for hours and you can taste the depth of flavor. Get the rare beef pho and watch the meat cook in the hot broth right at your table. Add plenty of hoisin and sriracha!',
    featured: false,
    published: true,
    hours: 'Mon-Sun: 10:00 AM - 10:00 PM',
  },
  {
    id: '8',
    name: 'Cafe Mogador',
    address: '101 St Marks Pl, New York, NY 10009',
    latitude: 40.7280,
    longitude: -73.9847,
    cuisineType: 'Mediterranean',
    priceRange: '$$',
    rating: 4.5,
    coverImage: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    tikTokUrl: 'https://www.tiktok.com/@example/video/1234567894',
    instagramUrl: 'https://www.instagram.com/p/example5/',
    reviewContent: 'East Village institution serving up incredible Moroccan food for 40+ years. The shakshuka is to die for - perfectly runny eggs in spiced tomato sauce. Their mint tea service is authentic and the tagines are so flavorful. Weekend brunch vibes are immaculate.',
    featured: false,
    published: true,
    hours: 'Mon-Thu: 9:00 AM - 12:00 AM, Fri-Sun: 9:00 AM - 1:00 AM',
  },
  {
    id: '9',
    name: 'Xi\'an Famous Foods',
    address: '81 St Marks Pl, New York, NY 10003',
    latitude: 40.7279,
    longitude: -73.9869,
    cuisineType: 'Chinese',
    priceRange: '$',
    rating: 4.6,
    coverImage: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
    tikTokUrl: 'https://www.tiktok.com/@example/video/1234567895',
    reviewContent: 'The hand-pulled noodles here are INSANE. Watch them stretch the noodles right in front of you! The spicy cumin lamb noodles are my go-to - perfectly chewy noodles, tender lamb, and that signature cumin-chili oil combo. Affordable and absolutely delicious.',
    featured: true,
    published: true,
    hours: 'Mon-Sun: 11:00 AM - 9:00 PM',
  },
  {
    id: '10',
    name: 'L\'Artusi',
    address: '228 W 10th St, New York, NY 10014',
    latitude: 40.7344,
    longitude: -74.0039,
    cuisineType: 'Italian',
    priceRange: '$$$$',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800',
    instagramUrl: 'https://www.instagram.com/p/example6/',
    reviewContent: 'Fine dining Italian that\'s worth every penny. The spaghetti with crab is divine, and their olive oil cake has ruined all other desserts for me. Amazing wine list too. Perfect for special occasions or when you want to treat yourself!',
    featured: false,
    published: true,
    hours: 'Mon-Sun: 5:00 PM - 11:00 PM',
  },
];

export const mockStats: SocialStats = {
  instagramFollowers: '125K',
  tikTokFollowers: '450K',
  totalReviews: 200,
  citiesCovered: 12,
};

export function getMockPlaceById(id: string): Place | undefined {
  return mockPlaces.find(place => place.id === id);
}

export function getMockFeaturedPlaces(): Place[] {
  return mockPlaces.filter(place => place.featured);
}
