import type { Place, SocialStats, Video, Event, TravelPost, VlogPost } from '../types';

export const mockPlaces: Place[] = [
  {
    id: '11',
    name: 'Don Sarang KBBQ',
    address: '2630 Old Denton Rd, Suite 140, Carrollton, TX 75007',
    latitude: 32.9857,
    longitude: -96.8903,
    cuisineType: 'Korean',
    priceRange: '$$$',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqrVQh/',
    reviewContent: 'My favorite flat grill KBBQ in Dallas! Unlike typical KBBQ spots, they cook on cast iron giving the meat a nice caramelized flavor. The meat quality is truly amazing and each set comes with side dishes, soybean stew, and fried rice. Not all-you-can-eat, but the quality makes it worth it.',
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Mon-Thu: 11AM-11PM, Fri-Sat: 11AM-12AM, Sun: 11AM-10PM',
    phone: '(972) 323-9306',
    website: 'https://instagram.com/donsarang.kbbq',
    dateReviewed: '2024-06-15',
  },
  {
    id: '12',
    name: 'Mamani',
    address: '2681 Howell St, Unit BU4, Dallas, TX 75204',
    latitude: 32.8002,
    longitude: -96.8005,
    cuisineType: 'French',
    priceRange: '$$$$',
    rating: 4.0,
    coverImage: 'https://cdn.sanity.io/images/2gup0440/production/1298cdf518e57eb72f41932810c7d74fe692882d-2048x1458.jpg',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqhEJc/',
    reviewContent: 'Michelin-starred French restaurant in Uptown! Led by Executive Chef Christophe De Lellis from Joel Robuchon in Las Vegas. Classic French cuisine rooted in Paris with French and Italian Riviera inspiration. They earned their Michelin star just 57 days after opening!',
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Tue-Thu: 5PM-9:30PM, Fri-Sat: 5PM-10PM',
    phone: '(469) 455-1435',
    website: 'https://mamanirestaurant.com',
    dateReviewed: '2024-06-20',
  },
  {
    id: '13',
    name: "Norman's Japanese Grill",
    address: '4002 Oak Lawn Ave, Dallas, TX 75219',
    latitude: 32.8103,
    longitude: -96.8118,
    cuisineType: 'Fusion',
    priceRange: '$$$$',
    rating: 4.2,
    coverImage: 'https://normansjapanese.com/wp-content/uploads/2025/10/DSCF6171-web-crop.jpg',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqhB4b/',
    reviewContent: 'Western-inspired Japanese raw bar and grill from Duro Hospitality. "If John Wayne were to open a Japanese restaurant this would be it." Features sashimi, handrolls, nigiri, robata skewers, and wood-fired grill items. The udon carbonara with smoked pork belly is a must-try!',
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Daily: 4PM-10PM (11PM weekends)',
    website: 'https://normansjapanese.com',
    dateReviewed: '2024-06-25',
  },
  {
    id: '14',
    name: 'Neko Yubu',
    address: '1499 Regal Row, Ste 105, Dallas, TX 75247',
    latitude: 32.8134,
    longitude: -96.8789,
    cuisineType: 'Korean',
    priceRange: '$',
    rating: 4.9,
    coverImage: 'https://www.nekoyubu.com/uploads/b/b38cc72c6dbe085f15fddf50f09503b2972a770c563024895c7aa47e5a0d7d3f/2024-12-28_17-07-51_1735427295.jpg',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqQJFn/',
    reviewContent: "The first and only yubu spot in Texas! Korean-style tofu pockets filled with seasoned rice and toppings like torched salmon, bulgogi, butter crab, and more. Think sushi wrapped in fried tofu. Started as a ghost kitchen inspired by the owner's mom's recipes. Takeout only!",
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Mon-Sat: 11AM-3PM, 4PM-8PM',
    website: 'https://nekoyubu.com',
    dateReviewed: '2024-07-01',
  },
  {
    id: '15',
    name: 'NADC Burger',
    address: '2908 McKinney Ave, Dallas, TX 75204',
    latitude: 32.8023,
    longitude: -96.7984,
    cuisineType: 'American',
    priceRange: '$$',
    rating: 4.5,
    coverImage: 'https://images.squarespace-cdn.com/content/v1/66b2709575b8187cb9050e55/479cce6c-137d-4c2b-8901-ee62ae733b4a/IMG_7488.JPG',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fq4sS5/',
    reviewContent: 'NADC (Not A Damn Chance) Burger - a chef-driven Wagyu smashburger concept from Michelin chef Phillip Frankland Lee and pro skater Neen Williams. Just one main item: a double-double with secret sauce, pickles, and slightly tamed jalapenos ($16). The beef tallow fries are incredible. Expect lines!',
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Daily: 11:30AM-12AM',
    website: 'https://nadcburger.com',
    dateReviewed: '2024-07-10',
  },
  {
    id: '16',
    name: 'Lucia',
    address: '287 N Bishop Ave, Dallas, TX 75208',
    latitude: 32.7527,
    longitude: -96.8267,
    cuisineType: 'Italian',
    priceRange: '$$$$',
    rating: 3.9,
    coverImage: 'https://www.luciadallas.com/img/media-lg/homepage_slider/Lucia_Dallas_Pasta_Italian_Salumi_Restaurant.02.jpg',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqHJCT/',
    reviewContent: 'First experience amazing, second experience kind of a miss. Intimate 50-seat fine dining Italian in Bishop Arts by James Beard nominee Chef David Uygur. House-cured salumi, homemade pasta, and fresh bread daily. Michelin Bib Gourmand. Menu changes constantly - no dish repeats.',
    featured: false,
    published: true,
    location: 'DFW',
    hours: 'Tue-Sat: 5PM-10PM',
    phone: '(214) 948-4998',
    website: 'https://luciadallas.com',
    dateReviewed: '2024-07-15',
  },
  {
    id: '17',
    name: 'Big Dash',
    address: '2693 Preston Rd, Frisco, TX 75034',
    latitude: 33.1007,
    longitude: -96.8236,
    cuisineType: 'Dessert',
    priceRange: '$',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqkqxf/',
    reviewContent: 'Amazing Middle Eastern desserts from a Syrian husband-wife team! Famous for their kunefeh (traditional filo pastry with cheese and syrup), baklava, and the viral Dubai chocolate bar - they make 700-800 bars daily! Also locations in Irving, Richardson, and Garland.',
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Daily: 12PM-11PM',
    phone: '(214) 407-8033',
    website: 'https://bigdash.com',
    dateReviewed: '2024-07-20',
  },
  {
    id: '18',
    name: 'Tatsu Dallas',
    address: '3309 Elm St, Unit 120, Dallas, TX 75226',
    latitude: 32.7873,
    longitude: -96.7751,
    cuisineType: 'Japanese',
    priceRange: '$$$$',
    rating: 3.5,
    coverImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fquXqD/',
    reviewContent: 'Michelin-starred omakase in Deep Ellum! Only 10 counter seats with Chef Tatsuya Sekiguchi (formerly of Michelin-starred Sushi Yasuda in NYC). Traditional edomae-style sushi - expect 13-15 pieces of nigiri plus appetizers and dessert. Reservations drop on the 1st and 15th at 8AM.',
    featured: false,
    published: true,
    location: 'DFW',
    hours: 'Tue-Sat: 5:30PM & 7:45PM seatings',
    website: 'https://tatsu-dallas.com',
    dateReviewed: '2024-07-25',
  },
  {
    id: '19',
    name: 'Pillar',
    address: '408 N Bishop Ave, Unit 108, Dallas, TX 75208',
    latitude: 32.7542,
    longitude: -96.8261,
    cuisineType: 'American',
    priceRange: '$$$$',
    rating: 3.8,
    coverImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqBNXH/',
    reviewContent: 'Modern American bistro in Bishop Arts from Chef Peja Krstic (of Michelin-awarded Mot Hai Ba). Seasonal menu with global influences. Try the beef tartare in crispy hashbrown cups and the iconic fried chicken with nduja cream. In the former Boulevardier space.',
    featured: false,
    published: true,
    location: 'DFW',
    hours: 'Tue-Thu: 5PM-10PM, Fri-Sat: 5PM-11PM, Sun: 5PM-9PM',
    phone: '(972) 803-3274',
    website: 'https://pillardallas.com',
    dateReviewed: '2024-08-01',
  },
  {
    id: '20',
    name: 'Written by the Seasons',
    address: '2681 Howell St, Unit BU2, Dallas, TX 75204',
    latitude: 32.8002,
    longitude: -96.8005,
    cuisineType: 'American',
    priceRange: '$$$',
    rating: 4.5,
    coverImage: 'https://14fc423a4c97ea6ac2e5cfbbef2647d5a957f384248b668e610de4e39a1e345d.cdn6.editmysite.com/uploads/b/14fc423a4c97ea6ac2e5cfbbef2647d5a957f384248b668e610de4e39a1e345d/quad_1740163973.png',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqhKfm/',
    reviewContent: 'Michelin-recommended farm-to-table spot at The Quad! Run by chef duo Melody Bishop and Dennis Kelly. Local seasonal ingredients with creative twists - vegetables get star billing here. Try the focaccia, and dishes with international flair like carrots with dukkah or branzino with harissa.',
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Mon: 3PM-9PM, Tue-Thu: 11:30AM-9PM, Fri: 11:30AM-10PM, Sat: 3PM-10PM',
    phone: '(214) 605-3131',
    website: 'https://writtenbytheseasons.com',
    dateReviewed: '2024-08-05',
  },
  {
    id: '21',
    name: 'Hampyong Cold Noodles',
    address: '2625 Old Denton Rd, Unit 464, Carrollton, TX 75007',
    latitude: 32.9851,
    longitude: -96.8901,
    cuisineType: 'Korean',
    priceRange: '$$',
    rating: 4.0,
    coverImage: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqBbF6/',
    reviewContent: 'Authentic Korean naengmyeon in Koreatown Carrollton! Self-service style - order, get a buzzer, pick up at counter. The Mul Naengmyeon is the star: chilled broth, chewy noodles, beef, pear, and egg. Refreshing and clean. Also try the Bibim Naengmyeon with tangy gochujang. No tipping!',
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Daily: 11AM-9:30PM',
    phone: '(972) 242-2445',
    dateReviewed: '2024-08-10',
  },
  {
    id: '22',
    name: 'Trades Delicatessen',
    address: '312 W Seventh St, Dallas, TX 75208',
    latitude: 32.7493,
    longitude: -96.8283,
    cuisineType: 'American',
    priceRange: '$$',
    rating: 4.5,
    coverImage: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fq9a5o/',
    reviewContent: "Obsessed with their French dip sandwich! From-scratch deli in Bishop Arts - they bake their own breads and bagels, smoke their meats and fish, and roast their coffee on-site. Love seeing their sandwiches of the month. French music, Paris vibes, but it's Dallas. Also try the Reuben!",
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Daily: 7AM-7PM',
    phone: '(972) 589-3525',
    website: 'https://tradesdeli.com',
    dateReviewed: '2024-08-15',
  },
  {
    id: '23',
    name: 'Spice Shawarma',
    address: '3901 W Northgate Dr, Irving, TX 75062',
    latitude: 32.8609,
    longitude: -96.9702,
    cuisineType: 'Mediterranean',
    priceRange: '$',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqa3HC/',
    reviewContent: 'Amazing shawarma food truck in Irving! Great service, great taste, and really good portion sizes. They serve shawarma, gyros, falafel, and rice bowls. Open late on weekends!',
    featured: true,
    published: true,
    location: 'DFW',
    hours: 'Daily: 11AM-11PM, Fri-Sat: 11AM-12AM',
    phone: '(945) 201-7300',
    website: 'https://instagram.com/spiceshawarma',
    dateReviewed: '2024-08-20',
  },
  {
    id: '24',
    name: 'Childish Bakery',
    address: '2625 Old Denton Rd, Ste 456, Carrollton, TX 75007',
    latitude: 32.9857,
    longitude: -96.8903,
    cuisineType: 'Korean',
    priceRange: '$',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqDyrS/',
    reviewContent: 'Korean bakery with amazing pastries and treats!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-08-25',
  },
  {
    id: '25',
    name: 'Samad Cafe',
    address: '2706 Manor Way, Dallas, TX 75235',
    latitude: 32.8401,
    longitude: -96.8489,
    cuisineType: 'Mediterranean',
    priceRange: '$$',
    rating: 4.6,
    coverImage: 'https://images.unsplash.com/photo-1540914124281-342587941389?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqmggJ/',
    reviewContent: 'Delicious Persian Mediterranean food!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-09-01',
  },
  {
    id: '26',
    name: 'Haidilao Hot Pot',
    address: '9244 Prestmont Pl, Unit 200, Frisco, TX 75035',
    latitude: 33.1351,
    longitude: -96.8236,
    cuisineType: 'Chinese',
    priceRange: '$$',
    rating: 3.0,
    coverImage: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqHRUD/',
    reviewContent: 'Chinese hot pot chain experience!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-09-05',
  },
  {
    id: '27',
    name: 'Evelyn',
    address: '1201 Turtle Creek Blvd, Dallas, TX 75207',
    latitude: 32.8052,
    longitude: -96.8041,
    cuisineType: 'American',
    priceRange: '$$$$',
    rating: 3.8,
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqaFS2/',
    reviewContent: 'Upscale steakhouse with great cocktail/appetizer vibes!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-09-10',
  },
  {
    id: '28',
    name: 'Domodomo Omakase',
    address: '2681 Howell St, Dallas, TX 75204',
    latitude: 32.8002,
    longitude: -96.8005,
    cuisineType: 'Japanese',
    priceRange: '$$$$',
    rating: 4.0,
    coverImage: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqUaKq/',
    reviewContent: 'Korean-influenced omakase experience!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-09-15',
  },
  {
    id: '29',
    name: 'Sandoitchi',
    address: '1604 Main St, Ste 110, Dallas, TX 75201',
    latitude: 32.7831,
    longitude: -96.7992,
    cuisineType: 'Japanese',
    priceRange: '$$',
    rating: 4.2,
    coverImage: 'https://images.unsplash.com/photo-1554433607-66b5efe9d304?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fq9A8o/',
    reviewContent: 'Japanese sandwich and coffee shop! *Disclaimer: downtown Dallas Neiman Marcus is not closing anymore*',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-09-20',
  },
  {
    id: '30',
    name: 'Dior Cafe',
    address: '58 Highland Park Village, Dallas, TX 75205',
    latitude: 32.8365,
    longitude: -96.8028,
    cuisineType: 'Cafe',
    priceRange: '$$$$',
    rating: 2.8,
    coverImage: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqqnfr/',
    reviewContent: 'Luxury cafe experience at Highland Park Village!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-09-25',
  },
  {
    id: '31',
    name: 'Zodiac Restaurant',
    address: '1618 Main St, FL 6, Dallas, TX 75201',
    latitude: 32.7834,
    longitude: -96.7988,
    cuisineType: 'American',
    priceRange: '$$$',
    rating: 4.5,
    coverImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqHTCa/',
    reviewContent: 'Classic American cuisine inside Downtown Neiman Marcus! *Disclaimer: downtown Dallas Neiman Marcus is no longer closing*',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-10-01',
  },
  {
    id: '32',
    name: 'Casa Brasa',
    address: '8111 Preston Rd, Dallas, TX 75225',
    latitude: 32.8682,
    longitude: -96.8028,
    cuisineType: 'Fusion',
    priceRange: '$$$$',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fq5gAx/',
    reviewContent: 'Japanese/Latin American fusion - the sushi is especially amazing here!',
    featured: true,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-10-05',
  },
  {
    id: '33',
    name: 'Prince St Pizza',
    address: '2820 N Henderson Ave, Dallas, TX 75206',
    latitude: 32.8214,
    longitude: -96.7873,
    cuisineType: 'Italian',
    priceRange: '$$',
    rating: 3.0,
    coverImage: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fq4yMK/',
    reviewContent: 'NYC-style pizza spot!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-10-10',
  },
  {
    id: '34',
    name: 'Burger Schmurger',
    address: '718 N Buckner Blvd, Dallas, TX 75218',
    latitude: 32.7937,
    longitude: -96.6917,
    cuisineType: 'American',
    priceRange: '$$',
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fquswP/',
    reviewContent: 'Amazing burgers!',
    featured: true,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-10-15',
  },
  {
    id: '35',
    name: 'Standard Pour',
    address: '2900 McKinney Ave, Dallas, TX 75204',
    latitude: 32.8054,
    longitude: -96.7972,
    cuisineType: 'Bar',
    priceRange: '$$',
    rating: 3.0,
    coverImage: 'https://images.unsplash.com/photo-1626645738196-c2a72c7e6e1a?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqhEeL/',
    reviewContent: 'Bar with great chicken tenders!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-10-20',
  },
  {
    id: '36',
    name: 'Skellig',
    address: '2409 N Henderson Ave, Dallas, TX 75206',
    latitude: 32.8185,
    longitude: -96.7882,
    cuisineType: 'Bar',
    priceRange: '$$',
    rating: 4.2,
    coverImage: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqk4t1/',
    reviewContent: 'Great bar food spot!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-10-25',
  },
  {
    id: '37',
    name: 'Vida Bowls',
    address: '10325 Garland Rd, Dallas, TX 75218',
    latitude: 32.8221,
    longitude: -96.6832,
    cuisineType: 'Cafe',
    priceRange: '$',
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqfarj/',
    reviewContent: 'Amazing smoothie bowls!',
    featured: true,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-11-01',
  },
  {
    id: '38',
    name: 'Mikes Gemini',
    address: '1906 S Harwood St, Dallas, TX 75215',
    latitude: 32.7699,
    longitude: -96.7872,
    cuisineType: 'Bar',
    priceRange: '$',
    rating: 3.9,
    coverImage: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqQcvx/',
    reviewContent: 'Dive bar with hotdogs. Mostly here for the vibes. Drinks are decent and I love that the hotdogs are beef but the breading could use some work.',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-11-05',
  },
  {
    id: '39',
    name: 'Honeybird',
    address: '1941 Preston Rd, Unit 1012, Plano, TX 75093',
    latitude: 33.0312,
    longitude: -96.8352,
    cuisineType: 'Korean',
    priceRange: '$$',
    rating: 4.5,
    coverImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqA4Mq/',
    reviewContent: 'Korean donut and sandwich shop!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-11-10',
  },
  // Coffee shops merged into food spots
  {
    id: '40',
    name: 'Pax & Beneficia',
    address: '2900 Canton St, Ste 130, Dallas, TX 75226',
    latitude: 32.7873,
    longitude: -96.7751,
    cuisineType: 'Coffee',
    priceRange: '$',
    rating: 4.0,
    coverImage: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqH1Yn/',
    reviewContent: 'Great coffee spot in Deep Ellum!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-11-15',
  },
  {
    id: '41',
    name: 'Flying Horse Cafe',
    address: '1401 Commerce St, Dallas, TX 75201',
    latitude: 32.7822,
    longitude: -96.8021,
    cuisineType: 'Coffee',
    priceRange: '$',
    rating: 3.5,
    coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqB8oP/',
    reviewContent: 'Small family owned business with the sweetest owner. Quick breakfast food on the go. Coffee can be hit or miss but was a staple when I worked in downtown Dallas.',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-11-20',
  },
  {
    id: '42',
    name: 'Khroma Coffee',
    address: '3401 Main St, Ste B, Dallas, TX 75226',
    latitude: 32.7863,
    longitude: -96.7721,
    cuisineType: 'Coffee',
    priceRange: '$',
    rating: 4.0,
    coverImage: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqUvHJ/',
    reviewContent: 'Cozy coffee shop with great vibes!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-11-25',
  },
  {
    id: '43',
    name: 'La Souq',
    address: '150 W Main St, Unit 900, Richardson, TX 75081',
    latitude: 32.9483,
    longitude: -96.7298,
    cuisineType: 'Coffee',
    priceRange: '$',
    rating: 4.3,
    coverImage: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqXaco/',
    reviewContent: 'Unique coffee and tea experience!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-12-01',
  },
  {
    id: '44',
    name: 'Chicha San Chen',
    address: '2225 Old Denton Rd, Ste 135, Carrollton, TX 75006',
    latitude: 32.9741,
    longitude: -96.8952,
    cuisineType: 'Coffee',
    priceRange: '$',
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1558857563-b371033873b8?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqu6pT/',
    reviewContent: 'I especially love their mango tea with jelly boba!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-12-05',
  },
  {
    id: '45',
    name: 'Hola Cafe',
    address: '413 N Tyler St, Dallas, TX 75208',
    latitude: 32.7524,
    longitude: -96.8297,
    cuisineType: 'Coffee',
    priceRange: '$$',
    rating: 4.2,
    coverImage: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqhJo7/',
    reviewContent: 'Lovely coffee spot in Bishop Arts!',
    featured: false,
    published: true,
    location: 'DFW',
    dateReviewed: '2024-12-10',
  },
];

export const mockVideos: Video[] = [];

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Balloon Museum',
    description: 'Immersive balloon art experience!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqCav5/',
    date: '2025-01-20',
  },
  {
    id: '2',
    title: 'The Eye Joule - Movie Night on the Lawn',
    description: 'Outdoor movie night experience!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fq98Es/',
    date: '2025-01-21',
  },
  {
    id: '3',
    title: 'Chelsea Corner Halloween Movie Night',
    description: 'Spooky movie night at Chelsea Corner!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqSWxh/',
    date: '2025-10-31',
  },
  {
    id: '4',
    title: 'Boogies Preview Event',
    description: 'Exclusive preview of Boogies!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqUMmy/',
    date: '2025-01-22',
  },
  {
    id: '5',
    title: "Hendy's on Henderson Preview Event",
    description: "Exclusive preview of Hendy's on Henderson!",
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqxoFn/',
    date: '2025-01-23',
  },
  {
    id: '6',
    title: 'Yayoi Kusama Museum',
    description: 'Immersive art experience at the Yayoi Kusama exhibit!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqPb2X/',
    date: '2025-01-24',
  },
  {
    id: '7',
    title: 'Harwood District Cinco de Mayo',
    description: 'Cinco de Mayo celebration at Harwood District!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fq5b5e/',
    date: '2025-05-05',
  },
  {
    id: '8',
    title: 'Live on the Lawn at The Village',
    description: 'Live on the Lawn event at The Village!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqyY7C/',
    date: '2025-01-25',
  },
  {
    id: '9',
    title: 'Movie Night at Griggs Park',
    description: 'Movie night at Griggs park!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqSe2Q/',
    date: '2025-01-26',
  },
  {
    id: '10',
    title: 'Komodo x Lalaland Event',
    description: 'Komodo x Lalaland collaboration event!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqP6jU/',
    date: '2025-01-27',
  },
  {
    id: '11',
    title: 'Schiaparelli Luncheon',
    description: 'Schiaparelli luncheon event!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fq42Qj/',
    date: '2025-01-28',
  },
  {
    id: '12',
    title: "Galentine's at My Apartment",
    description: "Galentine's celebration at my apartment!",
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqUbEb/',
    date: '2025-02-13',
  },
];

export const mockTravelPosts: TravelPost[] = [
  {
    id: '1',
    title: 'New York Trip',
    location: 'New York City',
    description: 'Fall adventures in NYC!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqudo9/',
    date: '2025-10-01',
  },
];

export const mockVlogPosts: VlogPost[] = [
  {
    id: '1',
    title: "Chloe's 30th Birthday",
    description: 'Celebrating the big 3-0!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqQMfJ/',
    date: '2025-01-01',
    city: 'DFW',
  },
  {
    id: '2',
    title: 'New York Trip',
    description: 'Fall adventures in NYC - October 2025!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqudo9/',
    date: '2025-10-01',
    city: 'NYC',
  },
  {
    id: '3',
    title: 'New York Trip Part 2',
    description: 'More NYC adventures - October 2025!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqX6N1/',
    date: '2025-10-02',
    city: 'NYC',
  },
  {
    id: '4',
    title: 'Dominican Republic Trip',
    description: 'Island adventures!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqmfrE/',
    date: '2025-01-10',
    city: 'Dominican Republic',
  },
  {
    id: '5',
    title: 'San Diego Trip',
    description: 'West coast adventures!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqkGcJ/',
    date: '2025-01-15',
    city: 'San Diego',
  },
  {
    id: '6',
    title: 'New York Trip Part 3',
    description: 'Even more NYC adventures!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqqkqq/',
    date: '2025-10-03',
    city: 'NYC',
  },
  {
    id: '7',
    title: 'Dallas Vlog',
    description: 'Adventures around DFW!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqPj44/',
    date: '2025-01-20',
    city: 'DFW',
  },
  {
    id: '8',
    title: 'Sunday Funday Vlog',
    description: 'Sunday funday adventures!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqUKuj/',
    date: '2025-01-26',
    city: 'DFW',
  },
  {
    id: '9',
    title: 'Day Off Vlog',
    description: 'Day off vibes!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqx9oq/',
    date: '2025-01-27',
    city: 'DFW',
  },
  {
    id: '10',
    title: 'Fort Worth Day',
    description: 'Exploring Fort Worth!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqqDw7/',
    date: '2025-01-28',
    city: 'DFW',
  },
  {
    id: '11',
    title: "Brother's Birthday Cake Vlog",
    description: "Celebrating my brother's birthday!",
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqAYVk/',
    date: '2025-01-29',
    city: 'DFW',
  },
  {
    id: '12',
    title: 'Tulum Travel Vlog',
    description: 'Adventures in Tulum, Mexico!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqk4LH/',
    date: '2025-02-01',
    city: 'Tulum',
  },
  {
    id: '13',
    title: 'NYC Vlog',
    description: 'More New York City adventures!',
    tikTokUrl: 'https://www.tiktok.com/t/ZP8fqu6jU/',
    date: '2025-02-05',
    city: 'NYC',
  },
];

export const mockStats: SocialStats = {
  instagramFollowers: '2.9K',
  tikTokFollowers: '27K',
  tikTokLikes: '1.6M',
  viewsThisYear: '2.8M',
  totalReviews: 200,
  citiesCovered: 12,
};

export function getMockPlaceById(id: string): Place | undefined {
  return mockPlaces.find(place => place.id === id);
}

export function getMockFeaturedPlaces(): Place[] {
  return mockPlaces.filter(place => place.featured);
}

export function getMockVideos(): Video[] {
  return mockVideos;
}

export function getMockEvents(): Event[] {
  return mockEvents;
}

export function getMockTravelPosts(): TravelPost[] {
  return mockTravelPosts;
}

export function getMockVlogPosts(): VlogPost[] {
  return mockVlogPosts;
}
